import type { Metadata } from "next";
import "./globals.css";
import { Layout } from "@/types/Layout";
import { geistMono, geistSans } from "./fonts";

export const metadata: Metadata = {
  title: "NextJS 15 - JavaScript Mastery",
  description: "Generated by create next app",
};

function RootLayout({ children }: Layout) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-4`}
      >
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
